apiVersion: v1
kind: Pod
metadata:
  name: cups
  namespace: cups
  labels:
    app: cups
spec:
  containers:
  - name: cups
    image: quay.io/robbmanes/cups:latest
    ports:
    - containerPort: 6631
      protocol: TCP
      name: ipp
    volumeMounts:
    - name: cups-config
      mountPath: /etc/cups/cupsd.conf
      subPath: cupsd.conf
    - name: cups-files
      mountPath: /etc/cups/cups-files.conf
      subPath: cups-files.conf
    - name: client-conf
      mountPath: /etc/cups/client.conf
      subPath: client.conf
    imagePullPolicy: Always
  volumes:
  - name: cups-config
    configMap:
      name: cups-conf
  - name: cups-files
    configMap:
      name: cups-files
  - name: client-conf
    configMap:
      name: client-conf
